#!/usr/bin/env bash
# Copy root CHANGELOG.md into docs/ and embed it for the Pages script
# (fetch of .md can fail offline / be blocked; embedded data always works).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/CHANGELOG.md"
DST="$ROOT/docs/CHANGELOG.md"
JS="$ROOT/docs/changelog-data.js"

if [[ ! -f "$SRC" ]]; then
  echo "error: $SRC not found" >&2
  exit 1
fi

mkdir -p "$ROOT/docs"
cp "$SRC" "$DST"

# Embed as a JS string (JSON-escaped) for reliable offline / Pages rendering.
python3 - "$SRC" "$JS" <<'PY'
import json, pathlib, sys
src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
text = src.read_text(encoding="utf-8")
dst.write_text(
    "// Auto-generated by scripts/sync_pages_changelog.sh — do not edit.\n"
    f"window.__CHANGELOG_MARKDOWN__ = {json.dumps(text, ensure_ascii=False)};\n",
    encoding="utf-8",
)
print(f"Wrote {dst}")
PY

echo "Synced $SRC → $DST"
